Feat/kickstarter
Koda-Finance/summitswap-core pull request #27
Opened 2022-08-08 08:20 UTC by erwin-huang

2022-09-05 16:05 UTC, umaismateen requested changes

2022-09-05 16:05 UTC, umaismateen commented on src/tests/SummitKickstarter.test.ts
> +        assert.equal(initialTotalContribution.toString(), "0");
We should also have an assert in this test that checks increase in contract balance and decrease in contributor balance. Same for the contribute Token test.

2022-09-05 16:05 UTC, umaismateen commented on src/tests/SummitKickstarter.test.ts
> +
We should also check if there is an increase in owner balance and check the change in contract balance === to change in receiver address

2022-09-05 16:16 UTC, umaismateen commented
<img width="806" alt="Screenshot 2022-09-05 at 9 08 04 PM" src="https://user-images.githubusercontent.com/58508079/188487429-b5786be8-82a1-4eda-8bf1-fffe48b82910.png">

We have to keep in mind that if we choose Koda as a paymentToken or any token with reflections. The amount transferred from wallet A to the smart contract will not be the same as the **_amount** because of the reflections. So it will be better if we don’t choose such a token as a paymentToken.

2022-09-06 02:40 UTC, erwin-huang commented on src/contracts/SummitKickstarter.sol
> +  mapping(address => bool) public isAdmin;
We can have admin in a specific Kickstarter, but they can only config the Kickstarter, but not approval or withdrawal fee

2022-09-06 02:47 UTC, erwin-huang commented on src/contracts/SummitKickstarter.sol
> +    }
Nice catch, I will update the `minContribution validation. 

We don't need to validate `_amount + totalContribution <= kickstarter.projectGoals`, if it reach the goals, we can still contribute, It's in the requirement

We don't need to validate the allowance, the IERC20 will validate it for us, it will throw a error, if the allowance is less than the transfer amount

2022-09-06 02:49 UTC, erwin-huang commented on src/contracts/SummitKickstarter.sol
> +
Why do we need to use percentage from minContribution?

2022-09-06 02:51 UTC, erwin-huang commented on src/contracts/SummitKickstarter.sol
> +  }
I think it's better to use `setApprovalStatus`, `setStatus` and `setKickstarterStatus`  is not specific, it's not a good naming

2022-09-06 03:49 UTC, erwin-huang commented on src/tests/SummitKickstarterFactory.test.ts
> +        .createProject(getKickstarter(), { value: SERVICE_FEE.add(1) });
We already have the test for create project with Token A Payment

2022-09-06 04:07 UTC, erwin-huang commented on src/tests/SummitKickstarter.test.ts
> +          ](getNewKickstarter(tokenA.address), 1, PERCENTAGE_FEE_AMOUNT, FIX_FEE_AMOUNT)
Which description is it?

2022-09-06 07:23 UTC, umaismateen commented on src/tests/SummitKickstarterFactory.test.ts
> +        .createProject(getKickstarter(), { value: SERVICE_FEE.add(1) });
Here we are just creating a Kickstarter and not testing excess fee refund. So, it is unnecessary to send an extra amount.

2022-09-06 07:25 UTC, umaismateen commented on src/tests/SummitKickstarter.test.ts
> +          ](getNewKickstarter(tokenA.address), 1, PERCENTAGE_FEE_AMOUNT, FIX_FEE_AMOUNT)
_should not set configProjectInfo when called by nonFactoryOwner or nonFactoryAdmin or nonAdmin_
because this function can only be called by factoryOwner and factoryAdmin.

2022-09-06 07:28 UTC, umaismateen commented on src/contracts/SummitKickstarter.sol
> +
I think it will be better to use projectGoals instead of minContribution.

2022-09-06 07:31 UTC, umaismateen commented on src/contracts/SummitKickstarter.sol
> +
I think it will better if we use projectGoals instead of minContribution wdyt ?

2022-09-06 23:20 UTC, umaismateen approved these changes

2022-09-07 07:59 UTC, merged